SHOW DATABASES;
DROP DATABASE IF EXISTS collage;
DROP DATABASE IF EXISTS campany;
DROP DATABASE IF EXISTS temp;
SHOW DATABASES;


CREATE DATABASE IF NOT EXISTS temp;
SHOW DATABASES;

DROP DATABASE IF EXISTS temp;
SHOW DATABASES;