SHOW DATABASES;
CREATE DATABASE DB1;
USE DB1;
CREATE TABLE IF NOT EXISTS Title(
	Id INT,
    Name VARCHAR(100),
    Age INT,
    City VARCHAR(100),
    
    PRIMARY KEY(Id)
);

INSERT INTO Title(Id,Name,Age,City) VALUES
	(001,"ABC",20,'Pune'),
    (002,"ABC",21,'Mumbai');
	
SELECT * FROM Title;


DROP TABLE IF EXISTS EMP;

CREATE TABLE IF NOT EXISTS EMP(
	Id INT,
    EMP_salary INT DEFAULT 1000000,
    FOREIGN KEY (Id) REFERENCES Title(Id)
);

INSERT INTO EMP(Id) VALUES
	(1),(2);
    
SELECT * FROM EMP; 

